// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarmaneTracker.Web.Data;

#nullable disable

namespace WarmaneTracker.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209181949_AddTargetStock")]
    partial class AddTargetStock
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("WarmaneTracker.Web.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Faction")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastFetchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LastMedianBuyoutGold")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LastMinBuyoutGold")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastQty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Realm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("WarmaneTracker.Web.Models.PriceHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MedianBuyoutGold")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinBuyoutGold")
                        .HasColumnType("TEXT");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("PriceHistory");
                });

            modelBuilder.Entity("WarmaneTracker.Web.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OnHand")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("Stock");
                });

            modelBuilder.Entity("WarmaneTracker.Web.Models.PriceHistory", b =>
                {
                    b.HasOne("WarmaneTracker.Web.Models.Item", "Item")
                        .WithMany("History")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WarmaneTracker.Web.Models.Stock", b =>
                {
                    b.HasOne("WarmaneTracker.Web.Models.Item", "Item")
                        .WithOne("Stock")
                        .HasForeignKey("WarmaneTracker.Web.Models.Stock", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WarmaneTracker.Web.Models.Item", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
