// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarmaneTracker.Web.Data;

#nullable disable

namespace WarmaneTracker.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212182609_AddScopeToPlanStepNotes")]
    partial class AddScopeToPlanStepNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("WarmaneTracker.Web.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Faction")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastFetchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LastMedianBuyoutGold")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LastMinBuyoutGold")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastQty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Realm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("WowItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.HasIndex("WowItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("WarmaneTracker.Web.Models.PlanStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CraftCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CraftWowItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromSkill")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfessionPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ToSkill")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionPlanId", "Order")
                        .IsUnique();

                    b.ToTable("PlanSteps");
                });

            modelBuilder.Entity("WarmaneTracker.Web.Models.PlanStepNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MinCharacterLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlanStepId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlanStepId");

                    b.ToTable("PlanStepNotes");
                });

            modelBuilder.Entity("WarmaneTracker.Web.Models.PriceHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MedianBuyoutGold")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinBuyoutGold")
                        .HasColumnType("TEXT");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("PriceHistory");
                });

            modelBuilder.Entity("WarmaneTracker.Web.Models.ProfessionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Faction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Realm")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProfessionPlans");
                });

            modelBuilder.Entity("WarmaneTracker.Web.Models.StepReagent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVendor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameHint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanStepId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("VendorPriceCopper")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WowItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlanStepId");

                    b.ToTable("StepReagents");
                });

            modelBuilder.Entity("WarmaneTracker.Web.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OnHand")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("Stock");
                });

            modelBuilder.Entity("WarmaneTracker.Web.Models.PlanStep", b =>
                {
                    b.HasOne("WarmaneTracker.Web.Models.ProfessionPlan", "ProfessionPlan")
                        .WithMany("Steps")
                        .HasForeignKey("ProfessionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfessionPlan");
                });

            modelBuilder.Entity("WarmaneTracker.Web.Models.PlanStepNote", b =>
                {
                    b.HasOne("WarmaneTracker.Web.Models.PlanStep", "PlanStep")
                        .WithMany("Notes")
                        .HasForeignKey("PlanStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanStep");
                });

            modelBuilder.Entity("WarmaneTracker.Web.Models.PriceHistory", b =>
                {
                    b.HasOne("WarmaneTracker.Web.Models.Item", "Item")
                        .WithMany("History")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WarmaneTracker.Web.Models.StepReagent", b =>
                {
                    b.HasOne("WarmaneTracker.Web.Models.PlanStep", "PlanStep")
                        .WithMany("Reagents")
                        .HasForeignKey("PlanStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanStep");
                });

            modelBuilder.Entity("WarmaneTracker.Web.Models.Stock", b =>
                {
                    b.HasOne("WarmaneTracker.Web.Models.Item", "Item")
                        .WithOne("Stock")
                        .HasForeignKey("WarmaneTracker.Web.Models.Stock", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WarmaneTracker.Web.Models.Item", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("WarmaneTracker.Web.Models.PlanStep", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("Reagents");
                });

            modelBuilder.Entity("WarmaneTracker.Web.Models.ProfessionPlan", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
